###
GET http://localhost:4999

###
POST http://localhost:4999/api/info?id=9
Content-Type: application/json

{
    "information": "My name is Pratham"
}

###
PUT http://localhost:4999/api/?word=pratham&banana=ripe?id=9
Content-Type: application/json

{
    "information": "My name is Pratham"
}


###
DELETE http://localhost:4999/delete/9?id=9
