###
GET http://localhost:4999

###
POST http://localhost:4999/api/info?id=8
Content-Type: application/json

{
    "information": "My name is Pratham"
}

###
PUT http://localhost:4999/api/?word=pratham&id=8
Content-Type: application/json

{
    "information": "My name is Pratham"
}


###
DELETE http://localhost:4999/delete?info=My%20name%20is%20Pratham&id=8

###
DELETE http://localhost:4999/delete?info=This%20is%20from%20the%20web%20client&id=8

