###
GET http://localhost:4999

###
POST http://localhost:4999/api/info?id=8
Content-Type: application/json

{
    "information": "My name is Pratham"
}

###
PUT http://localhost:4999/api/update?id=8
Content-Type: application/json
{
    "information": "You were using this website",
    "newInformation": "My name is James"
    
}
###
PUT http://localhost:4999/api/create?id=8
Content-Type: application/json
{
    "information": "My name is Pratham"
    
}

###
DELETE http://localhost:4999/delete?id=8



